name: webview_flutter_android
description: A Flutter plugin that provides a WebView widget on Android.
repository: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 3.8.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
        dartPluginClass: AndroidWebViewPlatform

dependencies:
  flutter:
    sdk: flutter
  simple_ast:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/simple_ast
  webview_flutter_platform_interface: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: 5.4.1
  pigeon: ^9.2.4
  code_template_processor:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/code_template_processor
  gen_api_impls:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/gen_api_impls
  simple_ast_generator:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/simple_ast_generator
